object WindowPluginForm: TWindowPluginForm
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'TWindowPluginForm'
  ClientHeight = 418
  ClientWidth = 568
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -14
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  OnShow = FormShow
  PixelsPerInch = 120
  TextHeight = 17
end
